// npx sequelize-cli db:migrate
// npx sequelize-cli db:seed:all
module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert("cards", [
      {
        title: "볼리비아 배낭여행",
        cardtext:
          "4분 모집해요. 3주간 다녀올 예정입니다. 우유니 소금사막에서 인증사진도 찍어요!",
        background: "7",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 1,
      },
      {
        title: "책 100권 읽기",
        cardtext: "지식을 쌓아보아요.",
        background: "9",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 3,
      },
      {
        title: "셀프 인테리어 도전",
        cardtext:
          "페인트, 도배, 바닥, 조명, 공간배치, 수납등등 같이 도전해봐요!",
        background: "18",
        completed: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 2,
      },
      {
        title: "누군가의 멘토 되어주기",
        cardtext:
          "내가 겪었던 일이나 걸어온 길을 걷고 있는 분들의 등대가 되어봅시다",
        background: "17",
        completed: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 4,
      },
      {
        title: "채소 직접 길러 먹어보기",
        cardtext: "매일 매일 자라는 채소를 직접 길러서 먹어봐요",
        background: "16",
        completed: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 5,
      },
      {
        title: "두바이에서 스카이다이빙하기",
        cardtext: "꼭 해봐야 합니다.",
        background: "15",
        completed: "2",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 3,
      },
      {
        title: "1년동안 매일 영어회화 한 챕터 외우기",
        cardtext: "매일 한 챕터 1년이면 360가지의 챕터를 외울 수 있습니다.",
        background: "14",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 2,
      },
      {
        title: "한달동안 금주, 금연하기",
        cardtext:
          "더 이상 미룰수만은 없다! 한달이라도 도전해 봅시다. 혹시 모르죠.",
        background: "13",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 1,
      },
      {
        title: "수영 자유형 숙달하기",
        cardtext: "물을 무서워 하지만 극복해보고 싶어요",
        background: "12",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 3,
      },
      {
        title: "오키나와에서 스쿠버다이빙하기",
        cardtext: "같이 버킷리스트를 이뤄봅시다.",
        background: "11",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 4,
      },
      {
        title: "3개월 채식하기",
        cardtext: "같이 버킷리스트를 이뤄봅시다.",
        background: "10",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 5,
      },
      {
        title: "스노우보드, 스키 고급 슬로프 도전",
        cardtext: "같이 버킷리스트를 이뤄봅시다.",
        background: "9",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 4,
      },
      {
        title: "핀란드에서 오로라 보기",
        cardtext: "같이 버킷리스트를 이뤄봅시다.",
        background: "8",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 3,
      },
      {
        title: "책 한권 쓰기",
        cardtext: "같이 버킷리스트를 이뤄봅시다.",
        background: "7",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 2,
      },
      {
        title: "마라톤 풀코스 완주",
        cardtext: "같이 버킷리스트를 이뤄봅시다.",
        background: "6",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 1,
      },
      {
        title: "나만의 신매뉴 개발",
        cardtext: "같이 버킷리스트를 이뤄봅시다.",
        background: "5",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 5,
      },
      {
        title: "분기마다 헌혈하기",
        cardtext: "같이 버킷리스트를 이뤄봅시다.",
        background: "4",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 3,
      },
      {
        title: "한라산 정상 등반",
        cardtext: "같이 버킷리스트를 이뤄봅시다.",
        background: "3",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 3,
      },
      {
        title: "프리미어리그 관람하기",
        cardtext: "같이 버킷리스트를 이뤄봅시다.",
        background: "2",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 2,
      },
      {
        title: "은하수 두눈으로 보기",
        cardtext: "같이 버킷리스트를 이뤄봅시다.",
        background: "1",
        completed: "0",
        createdAt: new Date(),
        updatedAt: new Date(),
        users_id: 1,
      },
    ]);
  },
  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("cards", null, {});
  },
};
